Functional Version of WaitCommand
chopshop-166/chopshoplib pull request #128
Opened 2022-05-17 23:04 UTC by JoeJanickiChSh

Adds a command that ends after a certain time period, much like a `WaitCommand`, but uses a time duration supplied by a `DoubleSupplier`.

2022-05-17 23:39 UTC, msoucy requested changes

2022-05-17 23:39 UTC, msoucy commented on core/src/main/java/com/chopshop166/chopshoplib/commands/FunctionalWaitCommand.java
> +    public FunctionalWaitCommand(final DoubleSupplier duration) {
Is `duration` the best name you can use for the argument? You use `duration` of a different type as a class member

2022-05-17 23:39 UTC, msoucy commented on core/src/main/java/com/chopshop166/chopshoplib/commands/FunctionalWaitCommand.java
> +        SendableRegistry.setName(this, getName());
Why is this necessary?

2022-05-18 00:35 UTC, msoucy commented on core/src/main/java/com/chopshop166/chopshoplib/commands/FunctionalWaitCommand.java
> +    public FunctionalWaitCommand(final DoubleSupplier durationSupplier) {
It would be nice to have a second constructor that also takes a name (and passes it to `setName`)

2022-06-07 23:02 UTC, msoucy commented
I would like to see factory functions added to `Commandable` for this.

2022-06-07 23:38 UTC, bot190 approved these changes

2022-06-15 00:18 UTC, msoucy requested changes

2022-06-15 00:18 UTC, msoucy commented on core/src/main/java/com/chopshop166/chopshoplib/commands/FunctionalWaitCommand.java
> +    public FunctionalWaitCommand(final DoubleSupplier durationSupplier, final String name) {
Please make the name the first argument

2022-07-12 22:31 UTC, msoucy approved these changes

2022-07-12 22:31 UTC, merged